sudo: required
services:
  - docker

before_install:
  - docker build -t frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "MyWebApp"
  env: "mywebapp-evn"
  bucket_name: "elasticbeanstalk-us-east-2-130110116752"
  bucket_path: "MyWebApp"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  
